export const SIGNIN = '/login';
// export const SIGNIN_FORNECEDOR = '/signin-fornecedor';
export const SIGNUP_CANAL = '/signup-canal';
export const SIGNUP_FORNECEDOR = '/signup-fornecedor';
export const FORGOTPASSWORD = '/forgot-password';
export const RESETPASSWORD = '/reset-password/:token';
export const ACTIVEUSER = '/active-user/:token'
export const DASHBOARD_CANAL = '/dashboard';
export const DASHBOARD_FORNECEDOR = '/dashboard-fornecedor';
export const MAIN = '/';
